### ISSUE TITLE
No Browser Versions in Selenoum UI and Web driver issue from code 

### ISSUE THREAD

**Issue by AadityaSeshadri** [aerokube/selenoid-ui#186]
Hello Team , 

I am new to Aerokube Selenoid . Appreciate for the best efforts done . 

Started using with docker compose with latest version 

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.9.2"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.8.0"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

After Running docker-compose up from the folder with browsers.json being in same folder 

{
  "chrome": {
    "command": "%s --whitelisted-ips='' --verbose",
    "files": {
      "linux": {
        "386": {
          "url": "http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux32.zip",
          "filename": "chromedriver"
        },
        "amd64": {
          "url": "http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip",
          "filename": "chromedriver"
        }
      },
      "darwin": {
        "amd64": {
          "url": "http://chromedriver.storage.googleapis.com/2.45/chromedriver_mac64.zip",
          "filename": "chromedriver"
        }
      },
      "windows": {
        "386": {
          "url": "http://chromedriver.storage.googleapis.com/2.45/chromedriver_win32.zip",
          "filename": "chromedriver.exe"
        },
        "amd64": {
          "url": "http://chromedriver.storage.googleapis.com/2.45/chromedriver_win32.zip",
          "filename": "chromedriver.exe"
        }
      }
    }
  },
  
  "firefox": {
    "command": "%s --host 127.0.0.1 --log debug",
    "files": {
      "linux": {
        "386": {
          "url": "https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux32.tar.gz",
          "filename": "geckodriver"
        },
        "amd64": {
          "url": "https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz",
          "filename": "geckodriver"
        }
      },
      "darwin": {
        "amd64": {
          "url": "https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz",
          "filename": "geckodriver"
        }
      },
      "windows": {
        "386": {
          "url": "https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-win32.zip",
          "filename": "geckodriver.exe"
        },
        "amd64": {
          "url": "https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-win64.zip",
          "filename": "geckodriver.exe"
        }
      }
    }
  },
  
  "opera": {
    "command": "%s --whitelisted-ips='' --verbose",
    "files": {
      "linux": {
        "amd64": {
          "url": "https://github.com/operasoftware/operachromiumdriver/releases/download/v.2.41/operadriver_linux64.zip",
          "filename": "operadriver_linux64/operadriver"
        }
      },
      "darwin": {
        "amd64": {
          "url": "https://github.com/operasoftware/operachromiumdriver/releases/download/v.2.41/operadriver_mac64.zip",
          "filename": "operadriver_mac64/operadriver"
        }
      },
      "windows": {
        "386": {
          "url": "https://github.com/operasoftware/operachromiumdriver/releases/download/v.2.41/operadriver_win32.zip",
          "filename": "operadriver_win32/operadriver.exe"
        },
        "amd64": {
          "url": "https://github.com/operasoftware/operachromiumdriver/releases/download/v.2.41/operadriver_win64.zip",
          "filename": "operadriver_win64/operadriver.exe"
        }
      }

    }
  },
  
  "safari": {
    "command": "%s",
    "files": {
      "darwin": {
        "amd64": {
          "url": "",
          "filename": "/usr/bin/safaridriver"
        }
      }
    }
  },

  "internet explorer": {
    "command": "%s",
    "files": {
      "windows": {
        "386": {
          "url": "http://selenium-release.storage.googleapis.com/3.14/IEDriverServer_Win32_3.14.0.zip",
          "filename": "IEDriverServer.exe"
        },
        "amd64": {
          "url": "http://selenium-release.storage.googleapis.com/3.14/IEDriverServer_x64_3.14.0.zip",
          "filename": "IEDriverServer.exe"
        }
      }
    }
  },
  
  "MicrosoftEdge": {
    "command": "%s --host=127.0.0.1 --verbose",
    "files": {
      "windows": {
        "386": {
          "url": "",
          "filename": "C:\\Windows\\System32\\MicrosoftWebDriver.exe"
        },
        "amd64": {
          "url": "",
          "filename": "C:\\Windows\\System32\\MicrosoftWebDriver.exe"
        }
      }
    }
  }
}

when navigated to 127.0.0.1 could see selenoid UI , but **Browsers List is empty**
also 

selenoid-ui_1  | 2019/08/03 07:37:49 Client added. 1 registered clients
selenoid-ui_1  | 2019/08/03 07:37:59 Client added. 2 registered clients
selenoid-ui_1  | 2019/08/03 07:38:02 Removed client. 1 registered clients
selenoid-ui_1  | 2019/08/03 07:39:52 Removed client. 0 registered clients
selenoid-ui_1  | 2019/08/03 07:39:53 Client added. 1 registered clients

when running from my code 
"URI.create("http://172.17.0,1:4444/wd/hub").toURL(),"
browser driver instance could not be started , almost spent a day time to look into ... have an critical project looking to implement .

Please help me on this and save my time .Understand its some minor configuration issue . 

earlier reply much appreciated

thanks

**Comment by AadityaSeshadri** [comment]
Selenium error 

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

**Comment by vania-pooh** [comment]
@AadityaSeshadri this is not the correct `browsers.json` - the file you are using is an internal `cm` tool file. You have to use `browsers.json` described in documentation: https://aerokube.com/selenoid/latest/#_browsers_configuration_file Using CM tools it could be generated as follows:
```
$ ./cm selenoid configure --vnc
```

**Comment by AadityaSeshadri** [comment]
when i tried with cm file with below commands it works 



./cm selenoid start --vnc
./cm selenoid-ui start 


Please help me knowing how this to be dealt with Dockercompose ....also help me knowing if docker compose

**Comment by vania-pooh** [comment]
@AadityaSeshadri have you seen this? https://aerokube.com/selenoid/latest/#_selenoid_with_docker_compose

**Comment by AadityaSeshadri** [comment]
Hello Ivan ,

Thanks for your kindly help to reply promptly .

I made changes as per document . My bad could not see it on an urgent
implementation for an PoC.

Currently browser json is as below

{
"chrome": {
"default": "75.0",
"versions": {
"75.0": {
"image": "selenoid/vnc:chrome_75.0",
"port": "4444",
"tmpfs": {"/tmp": "size=512m"},
"path" : "/wd/hub",
"hosts" : ["http://selenoid"],
"shmSize" : 268435456,
"cpu" : "1.0"
}
}
}
}


and docker-compose.yml


version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json",
"-video-output-dir", "/opt/selenoid/video", "-log-output-dir",
"/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui
    ports:
      - "8080:8080"
    command: -selenoid-uri http://selenoid:4444




but still i get below issue



selenoid-ui_1  | 2019/08/03 13:14:06 [ERROR] [Can't get status: Get
http://selenoid:4444/status: dial tcp: lookup selenoid on
192.168.65.1:53: no such host]
selenoid-ui_1  | 2019/08/03 13:14:06 Client added. 1 registered clients
selenoid-ui_1  | 2019/08/03 13:14:06 [ERROR] [Can't get status: Get
http://selenoid:4444/status: dial tcp: lookup selenoid on
192.168.65.1:53: no such host]
selenoid-ui_1  | 2019/08/03 13:14:06 Removed client. 0 registered clients


also in selenium UI browsers list is not getting fetched(says loading...)


Please help me to proceed this .

Have nice day

Regards,
Aaditya

**Comment by AadityaSeshadri** [comment]
hello Aerokube/Selenoid-Ui team ,

almost tried all ways and facing same issues again .


please let me know sample browser json and docker-compose including
selenoid and selenoid UI .

along please tell me which host entry to be added and which URL to be used
in script to call tests with port 4444

Quick help much appreciated:)


Regards,
Aaditya

**Comment by lanwen** [comment]
@AadityaSeshadri did you solve your issue? Did you try to add dependency between containers explicitly?

**Comment by sonamqaautomation** [comment]
Try this dom-compose.yml , this worked like a charm:-
version: '3'
services:
  selenoid:
   network_mode: bridge
   image: aerokube/selenoid
   volumes:
     - "/C/Users/sonam/Documents/newselenoid:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/C/Users/sonam/Documents/newselenoid/video:/opt/selenoid/video"
   environment:
     - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/sonam/Documents/newselenoid/video
     - TZ=Europe/Amsterdam
   command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
   ports:
     - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

**Comment by jimbalatero** [comment]
I have this config and still doesn't work

```
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest
    volumes:
      - "./docker/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./tests/_output/video:/opt/selenoid/video"
      - "./tests/_output/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenium/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
```

Error is 

```
2021/09/17 14:09:23 [INIT] [Listening on :8080]

2021/09/17 14:10:59 Client added. 1 registered clients

2021/09/17 14:11:06 [ERROR] [Can't get status: context deadline exceeded]

2021/09/17 14:11:09 [ERROR] [Can't get status: Get "http://selenoid:4444/status": dial tcp: lookup selenoid on 192.168.65.5:53: read udp 172.17.0.2:51143->192.168.65.5:53: i/o timeout]

2021/09/17 14:11:09 [ERROR] [Can't get status: Get "http://selenoid:4444/status": dial tcp: lookup selenoid on 192.168.65.5:53: read udp 172.17.0.2:51143->192.168.65.5:53: i/o timeout]

2021/09/17 14:11:16 [ERROR] [Can't get status: context deadline exceeded]

2021/09/17 14:11:21 [ERROR] [Can't get status: context deadline exceeded]

2021/09/17 14:11:26 [ERROR] [Can't get status: context deadline exceeded]

2021/09/17 14:11:31 [ERROR] [Can't get status: context deadline exceeded]

2021/09/17 14:11:36 [ERROR] [Can't get status: context deadline exceeded]

2021/09/17 14:11:41 [ERROR] [Can't get status: context deadline exceeded]
```

**Comment by vania-pooh** [comment]
@jimbalatero we described a working solution in docs: https://aerokube.com/selenoid/latest/#_selenoid_with_docker_compose Any customization is your responsibility.

**Comment by gravity-api** [comment]
I am facing the same issue, the document you refer to does not provide the solution.
I am using the yaml from the documentation and the selenoid-ui still printing the same error. The only way to workaround it was to use the host IP.

If you have a working compose for selenoid and selenoid-ui, please share.

**Comment by vania-pooh** [comment]
@gravity-api for some users turning off Docker Compose 2 mode can help to resolve this.

**Comment by gravity-api** [comment]
Thank you for your response. The error **still persist** I have removed it and tried again with the same `yaml`.
![image](https://user-images.githubusercontent.com/59060103/143780370-f59596c6-6ba4-4358-bfd2-dd621dd976b4.png)

**Comment by vania-pooh** [comment]
@gravity-api working config is here: https://aerokube.com/selenoid/latest/#_selenoid_with_docker_compose You just need to make sure `--selenoid-uri` is pointing to Selenoid container.

**Comment by gravity-api** [comment]
It is pointing to Selenoid container. Furthermore, if I remove the `network_mode: bridge` it is working between the `selenoid` and `selenoid-ui`, but will not communicate with the driver. When I use my machine IP instead of container name, everything is working.

It seems that the service discovery is not working properly or I missed something.

OS: Windows 11
Docker: Latest 

```yaml
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

**Comment by gravity-api** [comment]
I was able to fix it by using the custom network compose file

```yaml
version: '3'
networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created
services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - "/C/DockerVolumes/Rhino/Seleniod:/etc/selenoid"
      - "/C/DockerVolumes/Rhino/Seleniod/Video:/opt/selenoid/video"
      - "/C/DockerVolumes/Rhino/Seleniod/Logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/C/DockerVolumes/Rhino/Seleniod/Video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      selenoid: null
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```
