### ISSUE TITLE
Health check does not work if you customize the listen port

### ISSUE THREAD

**Issue by giggio** [aerokube/selenoid-ui#297]
Because the healthcheck is testing port 8080, if you customize the listen port with `--listen` it will fail.

https://github.com/aerokube/selenoid-ui/blob/673c5d795b47c419433fcc303d872928b0268aee/healthcheck/main.go#L12-L15

**Comment by lanwen** [comment]
Why would you do that inside the default container? Can you give the usecase? I could imagine a custom container, but then its possible to override the healthcheck command as well

**Comment by giggio** [comment]
I am hosting it on port 80. This are the args:

````
--selenoid-uri=http://selenoid:4444 --listen :80 -allowed-origin *
````

Yes, can override the healthcheck, I hadn't thought of that. This is what I'm doing on Docker Compose:

````yaml
    healthcheck:
      test: ["CMD", "/health-check", "--uri", "http://localhost/ping"]
      interval: 60s
      timeout: 1s
      retries: 3
````

This solves my problem.

But would it be possible for the listen args propagate to the healthcheck, so we don't have to customize it?
