### ISSUE TITLE
Can't get status: invalid character 'B' looking for beginning of value

### ISSUE THREAD

**Issue by Igorverizub** [aerokube/selenoid-ui#391]
Hello! In our project, we have an error in solenoid-ui and ggr-ui. Please help with this problem.
SELENOID UI - ` [ERROR] [Can't get status: invalid character 'B' looking for beginning of value]`
GGR UI - `[STATUS] [Unknown quota user: unknown] [192.168.16.5]`

Deploy.yml
```
  - name: Create a docker network
      docker_network:
        name: selenium_{{ env }}

  - name: Copy browsers.json file to the server
    copy:
      src: "../browsers.json"
      dest: "/opt/deploy/qa/browsers.json"

  - name: Copy quota config to the server
    copy:
      src: "../grid-router"
      dest: "/opt/deploy/qa/"

  - name: Start Selenoid GGR container
    docker_container:
      name: "selenium_ggr_{{ env }}"
      hostname: "ggr"
      image: "aerokube/ggr"
      state: started
      recreate: true
      pull: true
      purge_networks: "yes"
      exposed_ports:
      - 4444
      volumes:
      - /opt/deploy/qa/grid-router/:/etc/grid-router
      networks:
      - name: "selenium_{{ env }}"
      labels:
        environment: "{{ env }}"
        service: "ggr"
        project: "selenium"
        tier: "qa"

  - name: Start Selenoid GGR UI container
    docker_container:
      name: "selenium_ggr-ui_{{ env }}"
      image: "aerokube/ggr-ui"
      state: started
      recreate: true
      pull: true
      purge_networks: "yes"
      exposed_ports:
      - 8888
      volumes:
      - /opt/deploy/qa/grid-router/quota/:/etc/grid-router/quota
      networks:
      - name: "selenium_{{ env }}"
      labels:
        environment: "{{ env }}"
        service: "ggr-ui"
        project: "selenium"
        tier: "qa"

  - name: Start Selenoid container
    docker_container:
      name: "selenium_hub_{{ env }}"
      hostname: "hub"
      image: "aerokube/selenoid"
      privileged: true
      state: started
      recreate: true
      pull: true
      purge_networks: "yes"
      exposed_ports:
      - 5555
      volumes:
      - /opt/deploy/qa/:/etc/selenoid/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      networks:
      - name: "selenium_{{ env }}"
      command: ["--listen", ":5555", "-limit", "12", "-container-network", "selenium_{{ env }}"]
      labels:
        environment: "{{ env }}"
        service: "hub"
        project: "selenium"
        tier: "qa"

  - name: Start Selenoid web UI container
    docker_container:
      name: "selenium_hub-ui_{{ env }}"
      image: "aerokube/selenoid-ui"
      state: started
      pull: true
      purge_networks: "yes"
      ports:
      - 127.0.0.1:8081:8080
      networks:
      - name: "selenium_{{ env }}"
      command: ["--webdriver-uri", "http://selenium_ggr_{{ env }}:4444", "--status-uri", "http://selenium_ggr-ui_{{ env }}:8888"]
      labels:
        environment: "{{ env }}"
        service: "hub-ui"
        project: "selenium"
        tier: "qa"
```
