### ISSUE TITLE
SSE Unknown over NGINX and TLS

### ISSUE THREAD

**Issue by fniko** [aerokube/selenoid-ui#442]
Hello,
I like Selenoid and Selenoid-ui, so I wanted to use it behind domain name and with HTTPS (TLS) support.
I am able to see dashboard and run tests, however SSE status is Unknown so no new tests are displayed without page refresh.

Is there any guide or fix of this issue?

Configuration below:
We orchestrate docker containers with selenoid and selenoid-ui over docker-compose
**docker-compose.yml**
```
version: '3'
networks:
  selenoid_network:
    name: selenoid_network
    driver: bridge
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    networks:
      - selenoid_network
    container_name: selenoid
    ports:
      - "4445:4444"
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [ "-conf","/etc/selenoid/browsers.json","-container-network", "selenoid_network" ]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    networks:
      - selenoid_network
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri","http://selenoid:4444" ]
```

**Nginx configuration**
_Please note, we wanted to access Selenoid over regular port 4444, so thats why it's locally mapped to 4445 and "forwarded" un the nginx config._
```
add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";

upstream websocket-servers {
    server 127.0.01:8080;
}

# Selenoid UI over HTTPS
server {
    listen 443;
    server_name example.com;

    ssl on;
    ssl_certificate         /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/fullchain.pem;

    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 5m;
    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "ECDHE...

    ssl_dhparam /etc/nginx/dhparams.pem;
    ssl_prefer_server_ciphers on;

    root /var/www/example.com;
    index index.html index.htm;

    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        proxy_connect_timeout 600;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
    }
}

# Selenoid over HTTPS
server {
    listen 4444;
    server_name example.com;

    ssl on;
    ssl_certificate         /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/fullchain.pem;

    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 5m;
    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "ECDHE...

    ssl_dhparam /etc/nginx/dhparams.pem;
    ssl_prefer_server_ciphers on;

    root /var/www/example.com;
    index index.html index.htm;

    location / {
        proxy_pass http://127.0.0.1:4445;
    }
}
```

EDIT: No erros in browsers Console nor Network tab - tested in Chrome / Firefox / Safari.
EDIT2: During refresh I have discovered error - it is shown only for few miliseconds during page refresh. I am investigating this error now.
![image](https://user-images.githubusercontent.com/34549825/124137985-819db000-da86-11eb-8cb4-006039efcf01.png)

EDIT3: Okay, I definitely think the issue is in `/events`. This URL is not available through NGINX, however from host VM, I am receiving updates after calling `curl 127.0.0.1:8080/events`. 

EDIT4: After some time (like 3 - 5 minutes), SSE turned green until refresh. I belive it's connected to the following request:
![image](https://user-images.githubusercontent.com/34549825/124141737-f0303d00-da89-11eb-93b8-5e89b3b406bc.png)
![image](https://user-images.githubusercontent.com/34549825/124142201-51581080-da8a-11eb-9ff9-af3f32629960.png)
![image](https://user-images.githubusercontent.com/34549825/124142398-78164700-da8a-11eb-9150-4b27713e5119.png)
