### ISSUE TITLE
Error connecting to SSE

### ISSUE THREAD

**Issue by evalalos** [aerokube/selenoid-ui#446]
Hi guys,
I have a problem with starting selenoid-ui, SSE has an issue. Thanks in advance

Attaching all logs:

Console log:
EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.
index.js:101 Error connecting to SSE http://localhost:8888/events

Docker container log:
2021/08/05 13:31:53 [INIT] [Listening on :8080]
2021/08/05 13:31:57 Client added. 1 registered clients
2021/08/05 13:31:57 Client added. 2 registered clients
2021/08/05 13:32:02 Client added. 3 registered clients
2021/08/05 13:32:02 Client added. 4 registered clients
2021/08/05 13:32:03 Removed client. 3 registered clients
.....

![selenoid](https://user-images.githubusercontent.com/47383413/128361016-4bc01dca-1370-4651-b4f4-7a2318939dc3.png)

**Comment by vania-pooh** [comment]
@evalalos do you have Nginx or another reverse proxy behind Selenoid UI?

**Comment by dvdvdmt** [comment]
Hello @vania-pooh it seems I have very similar problem with SSE.
I use this docker-compose.yml:
```yml
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/Documents/config/:/etc/selenoid/:ro"
    command: -limit 20 --timeout 3m
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8042:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```
After their start I see the errors in the selenoid-ui
![image](https://user-images.githubusercontent.com/8076700/137849376-7cb8ccb1-1c8f-4613-9839-0a5455bf9a4a.png)
Endpoint `http://selenoid:4444/status` response with an error: `{"errors":[{"msg":"can't get status"}],"version":"1.10.4[2021-10-10_08:53:47AM]"}`.
I'm using the latest Docker for Mac v4.1.1. 
Could you please give me any advise on what should I check to figure out what is the problem?
